spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://root:mDvh8oc5W5-FvmtBLOVBfvkdDPI2l0iCng3vI6YRM1S4n3z8@7bd1b5fa-5dde-46ec-90bc-1cbbb84aec26.asia-south1.firestore.goog:443/db-capstone-project?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}